{
  "menu_header":{
    "pl":{
      "label":null,
      "items":[
        {
          "id":"offer",
          "label":"Oferta",
          "type":"dropdown",
          "items":[
            {
              "id":"pillar_international",
              "label":"Transport międzynarodowy",
              "url":"/pl/transport-miedzynarodowy/"
            },
            {
              "id":"express",
              "label":"Transport ekspresowy",
              "url":"/pl/transport-ekspresowy/"
            },
            {
              "id":"adr",
              "label":"Transport ADR",
              "url":"/pl/transport-adr/"
            },
            {
              "id":"paletowy",
              "label":"Transport paletowy",
              "url":"/pl/transport-paletowy/"
            },
            {
              "id":"cennik",
              "label":"Cennik",
              "url":"/pl/cennik/"
            }
          ]
        },
        {
          "id":"routes",
          "label":"Trasy",
          "type":"dropdown",
          "items":[
            {
              "label":"Transport do Niemcy",
              "url":"/pl/transport-do-niemiec/",
              "country_code":"DE",
              "pinned":true
            },
            {
              "label":"Transport do Włochy",
              "url":"/pl/transport-do-wloch/",
              "country_code":"IT",
              "pinned":true
            },
            {
              "label":"Transport do Francja",
              "url":"/pl/transport-do-francji/",
              "country_code":"FR",
              "pinned":true
            },
            {
              "label":"Transport do Hiszpania",
              "url":"/pl/transport-do-hiszpanii/",
              "country_code":"ES",
              "pinned":true
            },
            {
              "label":"Transport do Holandia",
              "url":"/pl/transport-do-holandii/",
              "country_code":"NL",
              "pinned":false
            }
          ]
        },
        {
          "id":"blog",
          "label":"Blog",
          "url":"/pl/blog/"
        }
      ]
    },
    "fr":{
      "label":null,
      "items":[
        {
          "id":"offer",
          "label":"Offre",
          "type":"dropdown",
          "items":[]
        },
        {
          "id":"routes",
          "label":"Itinéraires",
          "type":"dropdown",
          "items":[]
        }
      ]
    },
    "de":{
      "label":null,
      "items":[
        {
          "id":"offer",
          "label":"Angebot",
          "type":"dropdown",
          "items":[]
        },
        {
          "id":"routes",
          "label":"Routen",
          "type":"dropdown",
          "items":[
            {
              "label":"Transport nach Deutschland",
              "url":"/de/transport-nach-deutschland/",
              "country_code":"DE",
              "pinned":true
            }
          ]
        }
      ]
    },
    "it":{
      "label":null,
      "items":[
        {
          "id":"offer",
          "label":"Offerta",
          "type":"dropdown",
          "items":[]
        },
        {
          "id":"routes",
          "label":"Percorsi",
          "type":"dropdown",
          "items":[]
        }
      ]
    },
    "en":{
      "label":null,
      "items":[
        {
          "id":"offer",
          "label":"Offer",
          "type":"dropdown",
          "items":[
            {
              "id":"pillar_international",
              "label":"International Transport",
              "url":"/en/international-transport/"
            }
          ]
        },
        {
          "id":"routes",
          "label":"Routes",
          "type":"dropdown",
          "items":[]
        }
      ]
    },
    "es":{
      "label":null,
      "items":[
        {
          "id":"offer",
          "label":"Oferta",
          "type":"dropdown",
          "items":[]
        },
        {
          "id":"routes",
          "label":"Rutas",
          "type":"dropdown",
          "items":[]
        }
      ]
    }
  },
  "menu_footer":{
    "pl":{
      "columns":{
        "Oferta":[
          {
            "id":"pillar_international",
            "label":"Transport międzynarodowy",
            "url":"/pl/transport-miedzynarodowy/"
          },
          {
            "id":"express",
            "label":"Transport ekspresowy",
            "url":"/pl/transport-ekspresowy/"
          },
          {
            "id":"adr",
            "label":"Transport ADR",
            "url":"/pl/transport-adr/"
          },
          {
            "id":"paletowy",
            "label":"Transport paletowy",
            "url":"/pl/transport-paletowy/"
          },
          {
            "id":"cennik",
            "label":"Cennik",
            "url":"/pl/cennik/"
          }
        ],
        "Kierunki":{
          "columns":[
            [
              {
                "label":"Francja",
                "url":"/pl/transport-do-francji/"
              },
              {
                "label":"Hiszpania",
                "url":"/pl/transport-do-hiszpanii/"
              },
              {
                "label":"Holandia",
                "url":"/pl/transport-do-holandii/"
              },
              {
                "label":"Niemcy",
                "url":"/pl/transport-do-niemiec/"
              },
              {
                "label":"Włochy",
                "url":"/pl/transport-do-wloch/"
              }
            ]
          ]
        },
        "Najpopularniejsze trasy":[
          {
            "label":"Łódź – Berlin",
            "url":"/pl/trasy/lodz-berlin/"
          },
          {
            "label":"Łódź – Mediolan",
            "url":"/pl/trasy/lodz-milano/"
          },
          {
            "label":"Łódź – Madryt",
            "url":"/pl/trasy/lodz-madrid/"
          },
          {
            "label":"Łódź – Paryż",
            "url":"/pl/trasy/lodz-paris/"
          },
          {
            "label":"Poznań – Hamburg",
            "url":"/pl/trasy/poznan-hamburg/"
          },
          {
            "label":"Warszawa – Rzym",
            "url":"/pl/trasy/warszawa-roma/"
          }
        ]
      }
    },
    "fr":{
      "columns":{
        "Offre":[],
        "Destinations":{
          "columns":[
            []
          ]
        },
        "Trajets populaires":[]
      }
    },
    "de":{
      "columns":{
        "Angebot":[],
        "Ziele":{
          "columns":[
            [
              {
                "label":"Deutschland",
                "url":"/de/transport-nach-deutschland/"
              }
            ]
          ]
        },
        "Beliebte Routen":[
          {
            "label":"Łódź – Berlin",
            "url":"/de/routen/lodz-berlin/"
          }
        ]
      }
    },
    "it":{
      "columns":{
        "Offerta":[],
        "Destinazioni":{
          "columns":[
            []
          ]
        },
        "Rotte popolari":[]
      }
    },
    "en":{
      "columns":{
        "Offer":[
          {
            "id":"pillar_international",
            "label":"International Transport",
            "url":"/en/international-transport/"
          }
        ],
        "Destinations":{
          "columns":[
            []
          ]
        },
        "Most popular routes":[
          {
            "label":"Łódź – Berlin",
            "url":"/en/routes/lodz-berlin/"
          },
          {
            "label":"Łódź – Milan",
            "url":"/en/routes/lodz-milan/"
          }
        ]
      }
    },
    "es":{
      "columns":{
        "Oferta":[],
        "Destinos":{
          "columns":[
            []
          ]
        },
        "Rutas populares":[]
      }
    }
  },
  "breadcrumbs":[
    {
      "slug":"/en/international-transport/",
      "trail":[
        {
          "label":"Home",
          "url":"/en/"
        },
        {
          "label":"International Transport",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/transport-miedzynarodowy/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport międzynarodowy",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/transport-ekspresowy/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport ekspresowy",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/transport-adr/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport ADR",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/transport-paletowy/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport paletowy",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/cennik/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Cennik",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/transport-do-niemiec/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport międzynarodowy",
          "url":"/pl/transport-miedzynarodowy/"
        },
        {
          "label":"Niemcy",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/transport-do-wloch/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport międzynarodowy",
          "url":"/pl/transport-miedzynarodowy/"
        },
        {
          "label":"Włochy",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/transport-do-francji/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport międzynarodowy",
          "url":"/pl/transport-miedzynarodowy/"
        },
        {
          "label":"Francja",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/transport-do-hiszpanii/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport międzynarodowy",
          "url":"/pl/transport-miedzynarodowy/"
        },
        {
          "label":"Hiszpania",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/transport-do-holandii/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport międzynarodowy",
          "url":"/pl/transport-miedzynarodowy/"
        },
        {
          "label":"Holandia",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/trasy/lodz-berlin/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport międzynarodowy",
          "url":"/pl/transport-miedzynarodowy/"
        },
        {
          "label":"Niemcy",
          "url":"/pl/transport-do-niemiec/"
        },
        {
          "label":"Łódź – Berlin",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/trasy/poznan-hamburg/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport międzynarodowy",
          "url":"/pl/transport-miedzynarodowy/"
        },
        {
          "label":"Niemcy",
          "url":"/pl/transport-do-niemiec/"
        },
        {
          "label":"Poznań – Hamburg",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/trasy/lodz-milano/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport międzynarodowy",
          "url":"/pl/transport-miedzynarodowy/"
        },
        {
          "label":"Włochy",
          "url":"/pl/transport-do-wloch/"
        },
        {
          "label":"Łódź – Mediolan",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/trasy/warszawa-roma/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport międzynarodowy",
          "url":"/pl/transport-miedzynarodowy/"
        },
        {
          "label":"Włochy",
          "url":"/pl/transport-do-wloch/"
        },
        {
          "label":"Warszawa – Rzym",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/trasy/lodz-paris/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport międzynarodowy",
          "url":"/pl/transport-miedzynarodowy/"
        },
        {
          "label":"Francja",
          "url":"/pl/transport-do-francji/"
        },
        {
          "label":"Łódź – Paryż",
          "url":null
        }
      ]
    },
    {
      "slug":"/pl/trasy/lodz-madrid/",
      "trail":[
        {
          "label":"Strona główna",
          "url":"/pl/"
        },
        {
          "label":"Transport międzynarodowy",
          "url":"/pl/transport-miedzynarodowy/"
        },
        {
          "label":"Hiszpania",
          "url":"/pl/transport-do-hiszpanii/"
        },
        {
          "label":"Łódź – Madryt",
          "url":null
        }
      ]
    },
    {
      "slug":"/en/routes/lodz-berlin/",
      "trail":[
        {
          "label":"Home",
          "url":"/en/"
        },
        {
          "label":"International Transport",
          "url":"/en/international-transport/"
        },
        {
          "label":"(DE)",
          "url":null
        },
        {
          "label":"Łódź – Berlin",
          "url":null
        }
      ]
    },
    {
      "slug":"/en/routes/lodz-milan/",
      "trail":[
        {
          "label":"Home",
          "url":"/en/"
        },
        {
          "label":"International Transport",
          "url":"/en/international-transport/"
        },
        {
          "label":"(IT)",
          "url":null
        },
        {
          "label":"Łódź – Milan",
          "url":null
        }
      ]
    },
    {
      "slug":"/de/transport-nach-deutschland/",
      "trail":[
        {
          "label":"Startseite",
          "url":"/de/"
        },
        {
          "label":"Internationaler Transport",
          "url":null
        },
        {
          "label":"Deutschland",
          "url":null
        }
      ]
    },
    {
      "slug":"/de/routen/lodz-berlin/",
      "trail":[
        {
          "label":"Startseite",
          "url":"/de/"
        },
        {
          "label":"Internationaler Transport",
          "url":null
        },
        {
          "label":"Deutschland",
          "url":"/de/transport-nach-deutschland/"
        },
        {
          "label":"Łódź – Berlin",
          "url":null
        }
      ]
    }
  ],
  "hub_updates":[
    {
      "hub_slug":"/pl/transport-do-niemiec/",
      "popular_routes":[
        "/pl/trasy/lodz-berlin/",
        "/pl/trasy/poznan-hamburg/"
      ]
    },
    {
      "hub_slug":"/pl/transport-do-wloch/",
      "popular_routes":[
        "/pl/trasy/lodz-milano/",
        "/pl/trasy/warszawa-roma/"
      ]
    },
    {
      "hub_slug":"/pl/transport-do-francji/",
      "popular_routes":[
        "/pl/trasy/lodz-paris/"
      ]
    },
    {
      "hub_slug":"/pl/transport-do-hiszpanii/",
      "popular_routes":[
        "/pl/trasy/lodz-madrid/"
      ]
    },
    {
      "hub_slug":"/pl/transport-do-holandii/",
      "popular_routes":[]
    },
    {
      "hub_slug":"/de/transport-nach-deutschland/",
      "popular_routes":[
        "/de/routen/lodz-berlin/"
      ]
    }
  ],
  "hreflang":[
    {
      "group_id":"gid1",
      "entries":[
        {
          "lang":"pl",
          "url":"/pl/trasy/lodz-berlin/"
        },
        {
          "lang":"en",
          "url":"/en/routes/lodz-berlin/"
        },
        {
          "lang":"de",
          "url":"/de/routen/lodz-berlin/"
        },
        {
          "lang":"x-default",
          "url":"/en/routes/lodz-berlin/"
        }
      ]
    },
    {
      "group_id":"gid2",
      "entries":[
        {
          "lang":"pl",
          "url":"/pl/trasy/poznan-hamburg/"
        },
        {
          "lang":"x-default",
          "url":"/pl/trasy/poznan-hamburg/"
        }
      ]
    },
    {
      "group_id":"gid3",
      "entries":[
        {
          "lang":"pl",
          "url":"/pl/trasy/lodz-milano/"
        },
        {
          "lang":"en",
          "url":"/en/routes/lodz-milan/"
        },
        {
          "lang":"x-default",
          "url":"/en/routes/lodz-milan/"
        }
      ]
    },
    {
      "group_id":"gid4",
      "entries":[
        {
          "lang":"pl",
          "url":"/pl/trasy/warszawa-roma/"
        },
        {
          "lang":"x-default",
          "url":"/pl/trasy/warszawa-roma/"
        }
      ]
    },
    {
      "group_id":"gid5",
      "entries":[
        {
          "lang":"pl",
          "url":"/pl/trasy/lodz-paris/"
        },
        {
          "lang":"x-default",
          "url":"/pl/trasy/lodz-paris/"
        }
      ]
    },
    {
      "group_id":"gid6",
      "entries":[
        {
          "lang":"pl",
          "url":"/pl/trasy/lodz-madrid/"
        },
        {
          "lang":"x-default",
          "url":"/pl/trasy/lodz-madrid/"
        }
      ]
    }
  ],
  "sitemap_xml":"<urlset><url><loc>/de/routen/lodz-berlin/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/de/transport-nach-deutschland/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/en/international-transport/</loc><lastmod>2025-01-01T00:00:00Z</lastmod></url><url><loc>/en/routes/lodz-berlin/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/en/routes/lodz-milan/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/cennik/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/transport-adr/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/transport-do-francji/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/transport-do-hiszpanii/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/transport-do-holandii/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/transport-do-niemiec/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/transport-do-wloch/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/transport-ekspresowy/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/transport-miedzynarodowy/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/transport-paletowy/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/trasy/lodz-berlin/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/trasy/lodz-madrid/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/trasy/lodz-milano/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/trasy/lodz-paris/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/trasy/poznan-hamburg/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url><url><loc>/pl/trasy/warszawa-roma/</loc><lastmod>2025-08-13T02:09:54Z</lastmod></url></urlset>",
  "delta":{
    "added":[
      "/de/routen/lodz-berlin/",
      "/de/transport-nach-deutschland/",
      "/en/routes/lodz-berlin/",
      "/en/routes/lodz-milan/",
      "/pl/cennik/",
      "/pl/transport-adr/",
      "/pl/transport-do-francji/",
      "/pl/transport-do-hiszpanii/",
      "/pl/transport-do-holandii/",
      "/pl/transport-do-niemiec/",
      "/pl/transport-do-wloch/",
      "/pl/transport-ekspresowy/",
      "/pl/transport-miedzynarodowy/",
      "/pl/transport-paletowy/",
      "/pl/trasy/lodz-berlin/",
      "/pl/trasy/lodz-madrid/",
      "/pl/trasy/lodz-milano/",
      "/pl/trasy/lodz-paris/",
      "/pl/trasy/poznan-hamburg/",
      "/pl/trasy/warszawa-roma/"
    ],
    "updated":[],
    "removed":[
      "/pl/stara-strona/"
    ]
  },
  "validation":{
    "errors":[
      "Brakujący hub (DE) dla leaf: /en/routes/lodz-berlin/ (lang=en)",
      "Brakujący hub (IT) dla leaf: /en/routes/lodz-milan/ (lang=en)"
    ],
    "warnings":[
      "Brak strony Pillar w języku de – breadcrumbs mogą wskazywać pusty URL dla: /de/transport-nach-deutschland/",
      "Brak strony Pillar w języku de – breadcrumbs mogą wskazywać pusty URL dla: /de/routen/lodz-berlin/",
      "Język de: istnieją huby, ale brak Pillara – rozważ dodanie strony Pillar dla poprawnego silosu i breadcrumbs."
    ]
  }
}
