name: runner-ping
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ ".github/workflows/runner_ping.yml" ]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Show environment
        shell: bash
        run: |
          set -euo pipefail; set -x
          uname -a
          python --version || true
          node --version || true
          echo "RUNNER OK"
